background #1a110f
selection_background #f1dfda
foreground #f1dfda
cursor #b9ab66
color0 #353433
color1 #ff572a
color2 #ffbe97
color3 #ffdfd2
color4 #b9ab66
color5 #f29082
color6 #ffbb85
color7 #efd2c7
color8 #b49e96
color9 #ff8766
color10 #ffd5bd
color11 #fff1ec
color12 #dcbc93
color13 #ffa99a
color14 #ffd2b4
color15 #ffffff